# Generated by Django 5.1.6 on 2025-04-05 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vehicle_engine_capacity_vehicle_fuel_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('owner', 'license_plate'), name='unique_plate_per_user'),
        ),
    ]
