# Generated by Django 5.1.6 on 2025-04-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_vehicle_year_vehicle_purchase_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='last_Service_date',
            new_name='last_service_date',
        ),
    ]
