# Generated by Django 5.1.6 on 2025-04-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_last_service_date_vehicle_last_service_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='engine_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
