# Generated by Django 5.1.6 on 2025-04-06 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_trip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
